### ISSUE TITLE
mvn package hangs at javadoc plugin

### ISSUE THREAD

**Issue by axtimwalde** [bigdataviewer/bigdataviewer-core#14]
At current master https://github.com/bigdataviewer/bigdataviewer-core/commit/434dce2fc36d0d97f0d5a33e607d11fce3049f0c

    mvn clean package

never finishes but hangs at

    [...]
    [INFO] Building jar: /home/saalfelds/workspace/big-data-viewer/core/target/bigdataviewer-core-2.0.2-SNAPSHOT-sources.jar
    [INFO] 
    [INFO] --- maven-source-plugin:2.3:jar-no-fork (attach-sources) @ bigdataviewer-core ---
    [WARNING] Artifact sc.fiji:bigdataviewer-core:java-source:sources:2.0.2-SNAPSHOT already attached to project, ignoring duplicate
    [INFO] 
    [INFO] --- maven-javadoc-plugin:2.9.1:jar (attach-javadocs) @ bigdataviewer-core ---

I have added an adjustment to a recent API change of the openconnectome service and an addition to the CATMAID backend and wanted to test mvn compliance outside Eclipse.  In Eclipse, the project builds and runs fine.  Ideas?

**Comment by tpietzsch** [comment]
@axtimwalde I fixed some problems with the merge. It should work now. Can you check?

In the future it would be good if you do this kind of merge via a PR so that I can fix problems before they lead to a non-compiling master.

One question: Your merge introduced this:
https://github.com/bigdataviewer/bigdataviewer-core/blob/master/src/main/java/bdv/spimdata/legacy/XmlIoSpimDataMinimalLegacy.java#L188-L193
The spimdata/legacy is there to make sure that datasets exported/published with early BDV versions would still load. I think there are no published datasets with the KNOSSOS backend? In this case I would remove these lines because all KNOSSOS datasets would use the current XML?

**Comment by axtimwalde** [comment]
@tpietzsch You are right abuot the pull request, sorry for the mess, I didn't have enough sleep yesterday.  The recent merges were a total pain in the neck and costed me hours of reading through every single line of code during which I may have missed stuff (rebase involved?) and I git frustrated.  Next time I'll do pull requests.

Yes, this comment is superfluous, I removed it.

Back to the original problem: mvn now succeeds.  I also tested to go back to the previous commit and tried again and, suprise, it also succeeds.  This is driving me crazy!  I also realized that mvn -e would have told me more (may be) and I did not come to this idea yesterday.  IS it expected that malformed JavaDoc brings mvn to a non-reporting halt?  That wouldn't be great.

Thanks for your quick help!

**Comment by tpietzsch** [comment]
@axtimwalde no, that shouldn't have happened. I never observed the halt myself, but I did only try mvn after I changed a few things. I thought initially that a duplicate class that had moved to spim_data and was reintroduced by the merge (https://github.com/bigdataviewer/bigdataviewer-core/commit/801cec1f43fd4385eb88d262c4f2a1c44f8ed101) might have caused it, but with different package name this couldn't have been the problem. So, actually, I have no idea what caused the halt for you... Could eclipse build have interfered somehow?
