### ISSUE TITLE
Exception in PainterThread when closing BDV

### ISSUE THREAD

**Issue by igorpisarev** [bigdataviewer/bigdataviewer-core#25]
Occasionally happened to me when I closed the BDV window:
```
Exception in thread "PainterThread" java.lang.NullPointerException
  at bdv.viewer.render.MultiResolutionRenderer.checkResize(MultiResolutionRenderer.java:366)
  at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:459)
  at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:417)
  at net.imglib2.ui.PainterThread.run(PainterThread.java:86)
```
Was able to reproduce a few more times by scrolling into the volume (forces to fetch and paint the data) and closing the window immediately.
Looks similar to https://github.com/saalfeldlab/bigwarp/issues/25

**Comment by tpietzsch** [comment]
This should be fixed now.

https://github.com/bigdataviewer/bigdataviewer-core/commit/71704d75f1c51cc492037a8d2e71e72734b2a6e5

**Comment by igorpisarev** [comment]
Hi @tpietzsch,
I tested it with 3.0.2 and faced another problem: now it deadlocks most of the time when I close the BDV window. Here are two thread dumps of the same run:
http://pastebin.com/uDgHbaMR - right after I tried to close the window
http://pastebin.com/LqXmxKz0 - at some later point in time; the window is still opened and frozen

My guess is that `painterThread.interrupt()` gets called when the rendering is active, thus the painter thread enters its `wait()` state later and never actually gets interrupted.

**Comment by tpietzsch** [comment]
Hi @igorpisarev,
you are right. It shouldn't be a problem unless the interrupted status is cleared during rendering (as I understand if it is set when entering `wait()` an `InterruptedException` is immediately thrown). But of course, unfortunately, it was consumed... I hope it is fixed by this commit: https://github.com/bigdataviewer/bigdataviewer-core/commit/f0115a373c2c8f45ae82d36d6d0c061f329dea97
I hope there is no other place that I missed.

Can you check whether the problem persists with 3.0.3?

**Comment by igorpisarev** [comment]
Thanks @tpietzsch, just tried it with 3.0.3 and it's fixed now.

**Comment by tpietzsch** [comment]
thanks @igorpisarev 👍
