### ISSUE TITLE
New State / UI : bdv hangs when calling state().addSource(sourceAndConverter)

### ISSUE THREAD

**Issue by NicoKiaru** [bigdataviewer/bigdataviewer-core#77]
As mentioned in the title, bdv hangs in the table-tree-cards-clean branch when adding programmatically a Source.

Here's a gist which reproduces the issue:

https://gist.github.com/NicoKiaru/4a32a21a12c720e8ff15cb0fdcae5af2

It's requiring two additional dependencies, that are used just to help display two example sources.

The lock is produced when the line ` bdv.getViewer().state().addSource(camera);` is called

>  please, attach visualVM, do a thread-dump, and send it to me.

I'd like to but I don't know how to do this... I debugged a bit and found that the hanging occurs in

https://github.com/bigdataviewer/bigdataviewer-core/blob/01dce589dd43ed246d0f3cfca03298f97a174f39/src/main/java/bdv/viewer/BasicViewerState.java#L1615

There I was blocked because it's hard to now which of the listener is causing the issue

**Comment by tpietzsch** [comment]
@NicoKiaru Thanks for exploring and reporting and the example! This is so helpful!!!

The deadlock should now be fixed (82e745b8fd2a090700705899b5e64393c8eceeaa)

Regarding the additional questions in your gist:

```
final ConverterSetup csBlob = BigDataViewer.createConverterSetup( blob, 0 );
// Why is setupid necessary ?
```
Legacy reasons. In the old `BrightnessDialog` (via `SetupAssignments`), the ConverterSetups are identified by unique ID instead of as objects. The IDs are also used, when de/serializing the ViewerState into a `.settings.xml` file. This will be hopefully deprecated and removed soon.

```java
// 4 - Set convertersetup callback:
// Is this the proper way to do it ?
bdv.getConverterSetups().put(blob,csBlob);
csBlob.setupChangeListeners().add((converterSetup) -> bdv.getViewer().requestRepaint());
csBlob.setDisplayRange(0,255);
```
Because you passed this to `BigDataViewer.open()`, the first two lines are unnecessary.
For the "camera" image that you add later, the correct way to register it is
```java
bdv.getViewer().state().addSource( camera );
final ConverterSetup csCamera = BigDataViewer.createConverterSetup( camera, 1 );
// this makes it visible to the new UI and sets up repaint listeners, etc:
bdv.getConverterSetups().put( camera, csCamera );
// this makes it visible to the old BrightnessDialog:
// (if you don't do it, nothing bad happens. It just doesn't show up in the old dialog)
bdv.getSetupAssignments().addSetup( csCamera );
```

--------------------

Regarding VisualVM, it is very useful for debugging deadlocks (among other things). You should definitely add it to your "toolkit". It is super easy to use. In this case, basically:
* After I run your example and it hangs, I start VisualVM
![Screenshot 2020-01-23 at 11 04 38](https://user-images.githubusercontent.com/622070/72979000-b5779f00-3dd7-11ea-9d94-a7781796aa49.png)
All running JVMs show up and I double-click on the "AddSourceTest" one to attach to it.
* In the Threads tab, it already has detected the deadlock:
![Screenshot 2020-01-23 at 11 05 02](https://user-images.githubusercontent.com/622070/72979225-29b24280-3dd8-11ea-9868-9fe0c9fefdc4.png)
* I click on the "Thread Dump" button and at the end of the dump, it gives you the dead-locked threads, complete with stack traces and the locks they hold/are waiting for
![Screenshot 2020-01-23 at 11 05 25](https://user-images.githubusercontent.com/622070/72979348-6a11c080-3dd8-11ea-8cce-4b6555815bb5.png)

**Comment by NicoKiaru** [comment]
Awesome, thanks for the quick fix and all the info! I'll have a look at visualVM

**Comment by NicoKiaru** [comment]
There's a new maybe related issue. Less annoying, because potentially it could be avoided by using the new UI and dropping the old one, but here it is:

https://github.com/bigdataviewer/bigdataviewer-core/issues/78
